apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongo-pvc
    labels:
        app: mongo
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi

