kind: pipeline
name: exort-api-server

steps:
- name: build
  image: thomasf/drone-mvn
  volumes:
  - name: cache
    path: /root/.m2
  - name: cache2
    path: /tmp/maven
  commands:
  - cd ./api_server
  - mvn clean package 

- name: docker
  image: plugins/docker
  settings: 
    username:
        from_secret: aliyun-docker-usr
    password:
        from_secret: aliyun-docker-pwd
    repo: registry.cn-shanghai.aliyuncs.com/exort/auth
    registry: registry.cn-shanghai.aliyuncs.com
    dockerfile: ./auth/Dockerfile
    tags:
        - 0.0.1

trigger:
  branch:
  - auth
  
volumes:
  - name: cache
    host:
      path: /home/ubuntu/repo
  - name: cache2
    host:
      path: /home/ubuntu/mvn_tmp

