kind: pipeline
name: exort

steps:
- name: build
  image: thomasf/drone-mvn
  volumes:
  - name: cache
    path: /root/.m2
  commands:
  - cd ./auth
  - mvn clean package docker:build

#- name: ssh
#  image: appleboy/drone-ssh
#  settings:
#    host: 212.64.27.71
#    username: ubuntu
#    password:
#        from_secret: server_pwd
#    script:
#        - sudo docker build -t exort/auth .

trigger:
  branch:
  - auth
  
volumes:
  - name: cache
    host:
      path: /home/ubuntu/repo
