kind: pipeline
name: exort-auth

steps:
- name: build
  image: thomasf/drone-mvn
  volumes:
  - name: cache
    path: /root/.m2
  - name: docker-sock
    path: /var/run/docker.sock
  - name: docker-cred
    path: /root/.docker/config.json
  - name: server-hosts
    path: /etc/hosts
  commands:
  - cd ./auth
  - mvn clean package docker:removeImage -DimageName=exort/auth docker:build -DpushImage

trigger:
  branch:
  - auth

volumes:
  - name: cache
    host:
      path: /home/ubuntu/repo
  - name: docker-sock
    host:
      path: /var/run/docker.sock
  - name: docker-cred
    host:
      path: /home/ubuntu/.docker/config.json
  - name: server-hosts
    host:
      path: /etc/hosts

---

kind: pipeline
name: exort-common

steps:
- name: mvndeploy
  image: thomasf/drone-mvn
  volumes:
  - name: cache
    path: /root/.m2
  - name: docker-sock
    path: /var/run/docker.sock
  - name: docker-cred
    path: /root/.docker/config.json
  - name: server-hosts
    path: /etc/hosts
  commands:
  - cd ./common
  - mvn clean deploy

trigger:
  branch:
  - common

volumes:
  - name: cache
    host:
      path: /home/ubuntu/repo
  - name: docker-sock
    host:
      path: /var/run/docker.sock
  - name: docker-cred
    host:
      path: /home/ubuntu/.docker/config.json
  - name: server-hosts
    host:
      path: /etc/hosts

---

kind: pipeline
name: exort-perm

steps:
- name: test
  when:
    event:
    - pull_request
  image: maven
  volumes:
  - name: cache
    path: /root/.m2
  - name: docker-sock
    path: /var/run/docker.sock
  - name: docker-cred
    path: /root/.docker/config.json
  - name: server-hosts
    path: /etc/hosts
  - name: env
    path: /env
  commands:
  - cd ./permission_manager
  - wget -nH -m --ftp-user=$(cat /env/ftp_user) --ftp-password=$(cat /env/ftp_pass) ftp://cirno.wang/perm
  - mv -f perm src/main/resources
  - mvn clean test

- name: build
  when:
    event:
    - push
  image: thomasf/drone-mvn
  volumes:
  - name: cache
    path: /root/.m2
  - name: docker-sock
    path: /var/run/docker.sock
  - name: docker-cred
    path: /root/.docker/config.json
  - name: server-hosts
    path: /etc/hosts
  - name: env
    path: /env
  commands:
  - cd ./permission_manager
  - wget -nH -m --ftp-user=$(cat /env/ftp_user) --ftp-password=$(cat /env/ftp_pass) ftp://cirno.wang/perm
  - mv -f perm src/main/resources
  - mvn clean package docker:removeImage -DimageName=exort/permission-manager docker:build -DpushImage

trigger:
  branch:
  - perm-mgr

volumes:
  - name: cache
    host:
      path: /home/ubuntu/repo
  - name: docker-sock
    host:
      path: /var/run/docker.sock
  - name: docker-cred
    host:
      path: /home/ubuntu/.docker/config.json
  - name: server-hosts
    host:
      path: /etc/hosts
  - name: env
    host:
      path: /home/ubuntu/env
