kind: pipeline
name: exort-api-server

steps:
- name: build-settings
  image: knives/drone-maven-setting
  settings:
    servers:
    - id: docker-hub
      username: 
        from_secret: docker_usr
      password: 
        from_secret: docker_pwd
  when:
    branch:
    - api-server

- name: build
  image: maven
  volumes:
  - name: cache
    path: /root/.m2
  commands:
  - cat settings.xml
  - cd ./api_server
  - mvn clean package docker:removeImage -DimageName=exort/api-server docker:build -DpushImage -s ../settings.xml
  when:
    branch:
    - api-server

- name: scp
  image: appleboy/drone-scp
  settings:
    host: 202.120.40.8
    port: 30720
    username: ubuntu
    secrets:
    - source: deploy_key
      target: scp_key
    target: /home/ubuntu/deploy/${DRONE_REPO}/
    source:
        - api_server/apiserver.yaml
  when:
    branch:
    - api-server

- name: ssh
  image: appleboy/drone-ssh
  settings:
    host: 202.120.40.8
    port: 30720
    username: ubuntu
    secrets:
    - source: deploy_key
      target: ssh_key
    script:
        - cd /home/ubuntu/deploy/${DRONE_REPO}/api_server
        - kubectl apply -f apiserver.yaml
  when:
    branch:
    - api-server
