kind: pipeline
name: exort

steps:
- name: build
  image: thomasf/drone-mvn
  volumes:
  - name: cache
    path: /root/.m2
  - name: docker-sock
    path: /var/run/docker.sock
  commands:
  - cd ./auth
  #- export DOCKER_HOST=tcp://docker:2375
  - mvn clean package docker:removeImage -DimageName=exort/auth docker:build

- name: push-image
  image: appleboy/drone-ssh
  settings:
    host: 212.64.27.71
    username: ubuntu
    password:
        from_secret: server_pwd
    script:
        - sudo docker push exort/auth

trigger:
  branch:
  - auth
  
volumes:
  - name: cache
    host:
      path: /home/ubuntu/repo
  - name: docker-sock
    host:
      path: /var/run/docker.sock
