kind: pipeline
name: exort-api-server

steps:
- name: build
  image: thomasf/drone-mvn
  volumes:
  - name: cache
    path: /root/.m2
  - name: cache2
    path: /tmp/maven
  commands:
  - cd ./api_server
  - mvn clean package 
  when:
    branch:
    - deploy_on

- name: scp
  image: appleboy/drone-scp
  settings:
    host: 
        from_secret: deploy_host
    port: 
        from_secret: deploy_port
    username: ubuntu
    key:
        from_secret: deploy_key
    target: /home/ubuntu/deploy/${DRONE_REPO}/
    source:
        - api_server/target/apiserver-0.1.jar
        - api_server/apiserver.yaml
        - api_server/Dockerfile
  when:
    branch:
    - deploy_on

- name: ssh
  image: appleboy/drone-ssh
  settings:
    host: 
        from_secret: deploy_host
    port: 
        from_secret: deploy_port
    username: ubuntu
    key:
        from_secret: deploy_key
    script:
        - export KUBECONFIG=$HOME/admin.conf
        - cd /home/ubuntu/deploy/${DRONE_REPO}/api_server
        #- sudo docker image rm exort/api-server
        - sudo docker build -t exort/api-server . 
        - kubectl apply -f apiserver.yaml
  when:
    branch:
    - deploy_on

volumes:
  - name: cache
    host:
      path: /home/ubuntu/repo
  - name: cache2
    host:
      path: /home/ubuntu/mvn_tmp

