kind: pipeline
name: exort-article-manager

steps:
- name: build
  image: thomasf/drone-mvn
  volumes:
  - name: cache
    path: /root/.m2
  - name: docker-sock
    path: /var/run/docker.sock
  - name: docker-cred
    path: /root/.docker/config.json
  - name: server-hosts
    path: /etc/hosts
  commands:
  - cd ./article_manager
  - mvn clean package docker:removeImage -DimageName=exort/article-manager docker:build -DpushImage

trigger:
  branch:
  - article-mgr

volumes:
  - name: cache
    host:
      path: /home/ubuntu/repo
  - name: docker-sock
    host:
      path: /var/run/docker.sock
  - name: docker-cred
    host:
      path: /home/ubuntu/.docker/config.json
  - name: server-hosts
    host:
      path: /etc/hosts

---

kind: pipeline
name: exort-auth

steps:
- name: build
  image: thomasf/drone-mvn
  volumes:
  - name: cache
    path: /root/.m2
  - name: docker-sock
    path: /var/run/docker.sock
  - name: docker-cred
    path: /root/.docker/config.json
  - name: server-hosts
    path: /etc/hosts
  - name: app-config
    path: /root/resources
  commands:
  - cd ./auth
  - rm -rf src/main/resources
  - cp -rf /root/resources/auth src/main/resources
  - mvn clean package docker:removeImage -DimageName=exort/auth docker:build -DpushImage

trigger:
  branch:
  - auth

volumes:
  - name: cache
    host:
      path: /home/ubuntu/repo
  - name: docker-sock
    host:
      path: /var/run/docker.sock
  - name: docker-cred
    host:
      path: /home/ubuntu/.docker/config.json
  - name: server-hosts
    host:
      path: /etc/hosts
  - name: app-config
    host:
      path: /home/ubuntu/exort

---

kind: pipeline
name: exort-association-member-manager

steps:
- name: build
  image: thomasf/drone-mvn
  volumes:
  - name: cache
    path: /root/.m2
  - name: docker-sock
    path: /var/run/docker.sock
  - name: docker-cred
    path: /root/.docker/config.json
  - name: server-hosts
    path: /etc/hosts
  - name: exort-resources
    path: /resources
  commands:
  - cd ./association_member_manager
  - rm -rf src/main/resources
  - cp -rf /resources/asso_mem_manage src/main/resources
  - mvn clean package docker:removeImage -DimageName=exort/association-member-manager docker:build -DpushImage

trigger:
  branch:
  - asso_mem_manage

volumes:
  - name: cache
    host:
      path: /home/ubuntu/repo
  - name: docker-sock
    host:
      path: /var/run/docker.sock
  - name: docker-cred
    host:
      path: /home/ubuntu/.docker/config.json
  - name: server-hosts
    host:
      path: /etc/hosts
  - name: exort-resources
    host:
      path: /home/ubuntu/exort


---

kind: pipeline
name: exort-common

steps:
- name: prtest
  when:
    event:
    - pull_request
  image: thomasf/drone-mvn
  volumes:
  - name: cache
    path: /root/.m2
  - name: docker-sock
    path: /var/run/docker.sock
  - name: docker-cred
    path: /root/.docker/config.json
  - name: server-hosts
    path: /etc/hosts
  commands:
  - cd ./common
  - mvn test

- name: mvndeploy
  when:
    event:
    - push
  image: thomasf/drone-mvn
  volumes:
  - name: cache
    path: /root/.m2
  - name: docker-sock
    path: /var/run/docker.sock
  - name: docker-cred
    path: /root/.docker/config.json
  - name: server-hosts
    path: /etc/hosts
  commands:
  - cd ./common
  - mvn clean deploy source:jar

trigger:
  branch:
  - common

volumes:
  - name: cache
    host:
      path: /home/ubuntu/repo
  - name: docker-sock
    host:
      path: /var/run/docker.sock
  - name: docker-cred
    host:
      path: /home/ubuntu/.docker/config.json
  - name: server-hosts
    host:
      path: /etc/hosts
---

kind: pipeline
name: exort-apiserver

steps:
- name: build
  image: thomasf/drone-mvn
  volumes:
  - name: cache
    path: /root/.m2
  - name: docker-sock
    path: /var/run/docker.sock
  - name: docker-cred
    path: /root/.docker/config.json
  - name: app-config
    path: /root/resources
  commands:
  - cd ./api_server
  - rm -rf src/main/resources
  - cp -rf /root/resources/apiserver src/main/resources
  - mvn clean package docker:removeImage -DimageName=exort/apiserver docker:build -DpushImage

trigger:
  branch:
  - api-server

volumes:
  - name: cache
    host:
      path: /home/ubuntu/repo
  - name: docker-sock
    host:
      path: /var/run/docker.sock
  - name: docker-cred
    host:
      path: /home/ubuntu/.docker/config.json
  - name: app-config
    host:
      path: /home/ubuntu/exort
