kind: pipeline
name: exort

steps:
- name: build
  image: thomasf/drone-mvn
  volumes:
  - name: cache
    path: /root/.m2
  commands:
  - cd ./auth
  - mvn clean package 
  - pwd

- name: docker
  image: plugins/docker
  settings: 
    username:
        from_secret: aliyun-docker-usr
    password:
        from_secret: aliyun-docker-pwd
    repo: registry.cn-shanghai.aliyuncs.com/exort/auth
    registry: registry.cn-shanghai.aliyuncs.com
    dockerfile: ./auth/Dockerfile
    tags:
        - latest
    commands:
    - ls ./auth

trigger:
  branch:
  - auth
  
volumes:
  - name: cache
    host:
      path: /home/ubuntu/repo

