kind: pipeline
name: exort-auth

steps:
- name: build
  image: thomasf/drone-mvn
  volumes:
  - name: cache
    path: /root/.m2
  - name: docker-sock
    path: /var/run/docker.sock
  - name: docker-cred
    path: /root/.docker/config.json
  - name: server-hosts
    path: /etc/hosts
  commands:
  - cd ./auth
  - mvn clean package docker:removeImage -DimageName=exort/auth docker:build -DpushImage

trigger:
  branch:
  - auth

volumes:
  - name: cache
    host:
      path: /home/ubuntu/repo
  - name: docker-sock
    host:
      path: /var/run/docker.sock
  - name: docker-cred
    host:
      path: /home/ubuntu/.docker/config.json
  - name: server-hosts
    host:
      path: /etc/hosts

---

kind: pipeline
name: exort-common

steps:
- name: prtest
  when:
    event:
    - pull_request
  image: thomasf/drone-mvn
  volumes:
  - name: cache
    path: /root/.m2
  - name: docker-sock
    path: /var/run/docker.sock
  - name: docker-cred
    path: /root/.docker/config.json
  - name: server-hosts
    path: /etc/hosts
  commands:
  - cd ./common
  - mvn test

- name: mvndeploy
  when:
    event:
    - push
  image: thomasf/drone-mvn
  volumes:
  - name: cache
    path: /root/.m2
  - name: docker-sock
    path: /var/run/docker.sock
  - name: docker-cred
    path: /root/.docker/config.json
  - name: server-hosts
    path: /etc/hosts
  commands:
  - cd ./common
  - mvn clean deploy source:jar

trigger:
  branch:
  - common

volumes:
  - name: cache
    host:
      path: /home/ubuntu/repo
  - name: docker-sock
    host:
      path: /var/run/docker.sock
  - name: docker-cred
    host:
      path: /home/ubuntu/.docker/config.json
  - name: server-hosts
    host:
      path: /etc/hosts

---

kind: pipeline
name: exort-association-manager

steps:
- name: build
  image: thomasf/drone-mvn
  volumes:
  - name: cache
    path: /root/.m2
  - name: docker-sock
    path: /var/run/docker.sock
  - name: docker-cred
    path: /root/.docker/config.json
  - name: server-hosts
    path: /etc/hosts
  commands:
  - cd ./association_manager
  - mvn clean package docker:removeImage -DimageName=exort/association-manager docker:build -DpushImage

trigger:
  branch:
  - association_dev

volumes:
  - name: cache
    host:
      path: /home/ubuntu/repo
  - name: docker-sock
    host:
      path: /var/run/docker.sock
  - name: docker-cred
    host:
      path: /home/ubuntu/.docker/config.json
  - name: server-hosts
    host:
      path: /etc/hosts
