apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-svc
spec:
  type: NodePort
  ports:
  - name: http
    port: 3307
    nodePort: 30721
    targetPort: http
  selector:
    app: mysql
