server:
  port: 8900

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exort?serverTimezone=UTC
    username: root
    password:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update

