apiVersion: v1
kind: Service
metadata:
  name: api-server-service
  labels:
    app: api-server
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30729
    targetPort: 8080
  selector:
    app: api-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - image: exort/api-server
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
